services:
  db:
    image: postgres:15
    restart: always
    container_name: memorial_db
    env_file: .env
    ports:
      - "5433:5432"
#    volumes:
#      - memorial_db:/var/lib/postgresql/data
  app:
    image: openjdk:17-slim
    container_name: memorial_app
    env_file: .env
    ports:
      - "8081:8080"
    volumes:
      - ./app.jar:/app/app.jar
    depends_on:
      - db
    restart: always
    command: ["java", "-jar", "/app/app.jar"]

#volumes:
#  memorial_db: